# Generated by Django 5.1 on 2024-08-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_comment_created_0e6ed4_idx',
            old_name='blog_comment_created_0e6ed4_idx',
        ),
    ]
