# Generated by Django 5.1 on 2024-08-20 19:42

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_account_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_comment_created_0e6ed4_idx',
            old_name='blog_comment_created_0e6ed4_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('تکنولوژی', 'تکنولوی'), ('زبان برنامه نویسی', 'زبان برنامه نویسی'), ('هوش مصنوعی', 'هوش مصنوعی'), ('بلاکچین', 'بلاکچین'), ('سایر', 'سایر')], default='سایر', max_length=20, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[600, 400], upload_to='post_image/'),
        ),
    ]
